
const Map asmaulHusnaText = {
  1: {'name': 'Ar-Rahman', 'desc': 'The Most Gracious'},
  2: {'name': 'Ar-Raheem', 'desc': 'The Most Merciful'},
  3: {'name': 'Al-Malik', 'desc': 'The King'},
  4: {'name': 'Al-Quddus', 'desc': 'The Most Holy'},
  5: {'name': 'As-Salaam', 'desc': 'The Source of Peace'},
  6: {'name': 'Al-Mu\'min', 'desc': 'The Guardian of Faith'},
  7: {'name': 'Al-Muhaymin', 'desc': 'The Protector'},
  8: {'name': 'Al-Aziz', 'desc': 'The Mighty'},
  9: {'name': 'Al-Jabbar', 'desc': 'The Compeller'},
  10: {'name': 'Al-Mutakabbir', 'desc': 'The Majestic'},
  11: {'name': 'Al-Khaliq', 'desc': 'The Creator'},
  12: {'name': 'Al-Bari', 'desc': 'The Evolver'},
  13: {'name': 'Al-Musawwir', 'desc': 'The Fashioner of Forms'},
  14: {'name': 'Al-Ghaffar', 'desc': 'The Forgiving'},
  15: {'name': 'Al-Qahhar', 'desc': 'The Subduer'},
  16: {'name': 'Al-Wahhab', 'desc': 'The Bestower'},
  17: {'name': 'Ar-Razzaq', 'desc': 'The Provider'},
  18: {'name': 'Al-Fattah', 'desc': 'The Opener'},
  19: {'name': 'Al-Alim', 'desc': 'The Knower of All'},
  20: {'name': 'Al-Qabid', 'desc': 'The Constrictor'},
  21: {'name': 'Al-Basit', 'desc': 'The Expander'},
  22: {'name': 'Al-Khafid', 'desc': 'The Abaser'},
  23: {'name': 'Ar-Rafi', 'desc': 'The Exalter'},
  24: {'name': 'Al-Mu\'izz', 'desc': 'The Bestower of Honor'},
  25: {'name': 'Al-Mudhill', 'desc': 'The Humiliator'},
  26: {'name': 'As-Sami', 'desc': 'The Hearer of All'},
  27: {'name': 'Al-Basir', 'desc': 'The Seer of All'},
  28: {'name': 'Al-Hakam', 'desc': 'The Judge'},
  29: {'name': 'Al-Adl', 'desc': 'The Just'},
  30: {'name': 'Al-Latif', 'desc': 'The Subtle'},
  31: {'name': 'Al-Khabir', 'desc': 'The All-Aware'},
  32: {'name': 'Al-Halim', 'desc': 'The Forbearing'},
  33: {'name': 'Al-Azim', 'desc': 'The Magnificent'},
  34: {'name': 'Al-Ghafur', 'desc': 'The Forgiver and Concealer of Faults'},
  35: {'name': 'Ash-Shakur', 'desc': 'The Rewarder of Thankfulness'},
  36: {'name': 'Al-Ali', 'desc': 'The Most High'},
  37: {'name': 'Al-Kabir', 'desc': 'The Most Great'},
  38: {'name': 'Al-Hafiz', 'desc': 'The Preserver'},
  39: {'name': 'Al-Muqit', 'desc': 'The Nourisher'},
  40: {'name': 'Al-Hasib', 'desc': 'The Accounter'},
  41: {'name': 'Aj-Jalil', 'desc': 'The Mighty'},
  42: {'name': 'Al-Karim', 'desc': 'The Generous'},
  43: {'name': 'Ar-Raqib', 'desc': 'The Watchful'},
  44: {'name': 'Al-Mujib', 'desc': 'The Responder to Prayer'},
  45: {'name': 'Al-Wasi', 'desc': 'The All-Comprehending'},
  46: {'name': 'Al-Hakim', 'desc': 'The Perfectly Wise'},
  47: {'name': 'Al-Wadud', 'desc': 'The Loving'},
  48: {'name': 'Al-Majid', 'desc': 'The Majestic'},
  49: {'name': 'Al-Ba\'ith', 'desc': 'The Resurrector'},
  50: {'name': 'Ash-Shahid', 'desc': 'The Witness'},
  51: {'name': 'Al-Haqq', 'desc': 'The Truth'},
  52: {'name': 'Al-Wakil', 'desc': 'The Trustee'},
  53: {'name': 'Al-Qawi', 'desc': 'The Strong'},
  54: {'name': 'Al-Matin', 'desc': 'The Firm'},
  55: {'name': 'Al-Wali', 'desc': 'The Friend'},
  56: {'name': 'Al-Hamid', 'desc': 'The Praiseworthy'},
  57: {'name': 'Al-Muhsi', 'desc': 'The Counter'},
  58: {'name': 'Al-Mubdi', 'desc': 'The Originator'},
  59: {'name': 'Al-Mu\'id', 'desc': 'The Restorer'},
  60: {'name': 'Al-Muhyi', 'desc': 'The Giver of Life'},
  61: {'name': 'Al-Mumit', 'desc': 'The Taker of Life'},
  62: {'name': 'Al-Hayy', 'desc': 'The Ever-Living'},
  63: {'name': 'Al-Qayyum', 'desc': 'The Sustainer'},
  64: {'name': 'Al-Wajid', 'desc': 'The Finder'},
  65: {'name': 'Al-Majid', 'desc': 'The Glorious'},
  66: {'name': 'Al-Wahid', 'desc': 'The One'},
  67: {'name': 'As-Samad', 'desc': 'The Eternal Refuge'},
  68: {'name': 'Al-Qadir', 'desc': 'The Powerful'},
  69: {'name': 'Al-Muqtadir', 'desc': 'The Determiner of All'},
  70: {'name': 'Al-Muqaddim', 'desc': 'The Expeditiously All-Arranger'},
  71: {'name': 'Al-Mu\'akhkhir', 'desc': 'The Delayer'},
  72: {'name': 'Al-Awwal', 'desc': 'The First'},
  73: {'name': 'Al-Akhir', 'desc': 'The Last'},
  74: {'name': 'Az-Zahir', 'desc': 'The Manifest'},
  75: {'name': 'Al-Batin', 'desc': 'The Hidden'},
  76: {'name': 'Al-Wali', 'desc': 'The Protecting Friend'},
  77: {'name': 'Al-Muta\'ali', 'desc': 'The Supreme'},
  78: {'name': 'Al-Barr', 'desc': 'The Doer of Good'},
  79: {'name': 'At-Tawwab', 'desc': 'The Acceptor of Repentance'},
  80: {'name': 'Al-Muntaqim', 'desc': 'The Avenger'},
  81: {'name': 'Al-Afuw', 'desc': 'The Pardoner'},
  82: {'name': 'Ar-Ra\'uf', 'desc': 'The Compassionate'},
  83: {'name': 'Malik-ul-Mulk', 'desc': 'The Owner of All Sovereignty'},
  84: {'name': 'Dhul-Jalali wal-Ikram', 'desc': 'The Lord of Majesty and Generosity'},
  85: {'name': 'Al-Muqsit', 'desc': 'The Equitable'},
  86: {'name': 'Al-Jami', 'desc': 'The Gatherer'},
  87: {'name': 'Al-Ghani', 'desc': 'The Self-Sufficient'},
  88: {'name': 'Al-Mughni', 'desc': 'The Enricher'},
  89: {'name': 'Al-Mani', 'desc': 'The Preventer of Harm'},
  90: {'name': 'Ad-Darr', 'desc': 'The Creator of The Harmful'},
  91: {'name': 'An-Nafi', 'desc': 'The Creator of Good'},
  92: {'name': 'An-Nur', 'desc': 'The Light'},
  93: {'name': 'Al-Hadi', 'desc': 'The Guide'},
  94: {'name': 'Al-Badi', 'desc': 'The Incomparable'},
  95: {'name': 'Al-Baqi', 'desc': 'The Lasting'},
  96: {'name': 'Al-Warith', 'desc': 'The Inheritor of All'},
  97: {'name': 'Ar-Rashid', 'desc': 'The Righteous Teacher'},
  98: {'name': 'As-Sabur', 'desc': 'The Patient'},
  99: {'name': 'Al-Haseeb', 'desc': 'The Reckoner'},
};

// This completes the list of the 99 names and descriptions of Asmaul Husna.
